#!/usr/bin/env bash
#
# Summary: Calls base file 
#
# Usage: call FILE [LANG {OPTIONS}]
#
# If LANG is present, sets it as the current one
# FILE must be a valid base file

# Save file name
file="$1"
shift

# If the language is specified,
# set it as the current one
if [[ $# -gt 0 ]]; then
	cfg/set-lang "$1"
	shift
fi

# Get current language
lang=$(cfg/get-lang)

if [[ $? -ne 0 ]]; then
	exit $?
fi

# Source base file
source "cfg/base/$file"
