#!/usr/bin/env bash
#
# Summary: Sets current language
#
# Usage: cfg/set-lang [LANG]
#
# Sets current language as LANG, if present

if [[ $# -eq 1 ]]; then
	echo "$1" > cfg/lang.cfg
	mkdir -p "cfg/langs/$1"
fi
