#!/usr/bin/env bash
#
# Summary: Display binary file path 
#
# Usage: ./bin [LANG {OPTIONS}]
#
# Calls individual source script for the language.
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

libexec/call bin "$@"
