#!/usr/bin/env bash
#
# Summary: Writes input to source code
#
# Usage: ./cat [LANG {OPTIONS}]
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

libexec/call cat "$@"
