#!/usr/bin/env bash
#
# Summary: Cleans temporary files
#
# Usage: ./clean
#
# Cleans code, configuration files etc

find bin/langs -name temp -type d -exec rm -rf {} \; 2>/dev/null
find bin -regex '.*\.dat' -type f -delete
