#!/usr/bin/env bash
#
# Summary: Remove all temporary files
#
# Usage: ./clearall {OPTIONS}
#
# Remove source code and configuration files from
# all the available languages

current=$(libexec/get-lang 2>/dev/null)

for lang in $(./list);
do
	./clear "$lang" "$@"
done

libexec/set-lang "$current"
