#!/usr/bin/env bash
#
# Summary: Removes temporary files
#
# Usage: ./clear [LANG {OPTIONS}]
#
# Removes code and configuration files
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

bin/call clear "$@"
