#!/usr/bin/env bash
#
# Summary: Copy contents of source code to clipboard
#
# Usage: ./clip [LANG {OPTIONS}]
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

libexec/call clip "$@"
