#!/usr/bin/env bash
#
# Summary:
# Competitive Programming Language-Agnostic Toolkit
#
# Usage:
# cplat command [[language] options]

# Get base directory
basedir=$(dirname "${BASH_SOURCE[0]}")

# If no command is passed
if [[ $# -eq 0 ]]; then
	# exit
	source "$basedir/libexec/err/6"
fi

# Save command
command="$1"
shift

# If command exists
if [[ -f "$basedir/libexec/base/$command" ]]; then

	# then, push base directory
	pushd "$basedir" > /dev/null

	# run the command and pass any additional options
	libexec/call "$command" "$@" 

	# and pop directory
	popd > /dev/null
else
	# else, exit
	source "$basedir/libexec/err/7"
fi
