#!/usr/bin/env bash
#
# Summary: Edit source code
#
# Usage: ./edit [LANG {OPTIONS}]
#
# Open source code in text editor.
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

libexec/call edit "$@"
