#!/usr/bin/env bash
#
# Summary: Run code
#
# Usage: ./run [LANG {OPTIONS}]
#
# Calls individual run script for the language
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

bin/call run "$@"
