#!/usr/bin/env bash
#
# Summary: Display source code path
#
# Usage: ./src [LANG {OPTIONS}]
#
# Call individual source script for the language.
#
# If LANG is ommitted, the current language is
# assumed, and no additional options are passed.

libexec/call src "$@" 
