#!/usr/bin/env bash

source tests/framework

T 'rm -f etc/lang'
F 'libexec/get-lang' 'No language is set'

for language in $(ls -1 lib); do
	T "cptk init $language"
	T 'libexec/get-lang' "^$language$"
done

END
