#!/usr/bin/env bash

source tests/framework

BEGIN_TEST

F 'libexec/get-lang' 'No language is set'

for language in `libexec/ls-langs`
do
	WRAP T "cptk init $language"
	T 'libexec/get-lang' '' "^$language$"
done

END_TEST
