#!/usr/bin/env bash

source tests/framework

BEGIN_TEST

T 'libexec/ls-langs'

T 'rm -rf lib/unknown-language'
F 'libexec/ls-langs | grep ^unknown-language$'
T 'mkdir lib/unknown-language'
F 'libexec/ls-langs | grep ^unknown-language$'
T 'rm -r lib/unknown-language'
F 'libexec/ls-langs | grep ^unknown-language$'

F '[ -d lib/newlang ]'
T 'mkdir lib/newlang'
T 'touch lib/newlang/path'
T 'libexec/ls-langs | grep ^newlang$'
T 'rm -r lib/newlang'
F 'libexec/ls-langs | grep ^newlang$'

END_TEST
