#!/usr/bin/env bash

source tests/framework

BEGIN_TEST

F 'libexec/set-lang' 'Missing <language> argument'
F 'libexec/set-lang ""' 'Unknown language'
F 'libexec/set-lang "."' 'Unknown language'
F 'libexec/set-lang ".."' 'Unknown language'
F 'libexec/set-lang "/"' 'Unknown language'
F 'libexec/set-lang "not-a-language"' 'Unknown language'

for language in `libexec/ls-langs`; do
	T "libexec/set-lang $language"
done

END_TEST
