#!/usr/bin/env bash

source tests/framework

F 'libexec/set-lang' 'Missing <language> argument'
F 'libexec/set-lang ""' 'Unknown language'
F 'libexec/set-lang "."' 'Unknown language'
F 'libexec/set-lang ".."' 'Unknown language'
F 'libexec/set-lang "/"' 'Unknown language'
F 'libexec/set-lang "not-a-language"' 'Unknown language'

for language in $(ls -1 lib); do
	T "libexec/set-lang $language"
done

END
