#!/usr/bin/env bash

source tests/framework

BEGIN_TEST

F 'libexec/subcall path' 'No language is set'

WRAP T 'cptk init c'
F 'libexec/subcall' 'Missing <command> argument'
F 'libexec/subcall unknown-command' "Language 'c' doesn't support command 'unknown-command'"

for language in `libexec/ls-langs`
do
	WRAP T "cptk init $language"
	T 'libexec/subcall path' '' '..*'
done

END_TEST
