#!/usr/bin/env bash
#
# Summary: prints usage information
#
# Usage: libexec/base/--help

echo "Usage: $programname <command> [<args>]"
echo ""
echo "Some useful commands are:"
echo "  init <language>    set current language"
echo "  path               print program path"
libexec/has-routine edit && \
echo "  edit               edit program"
echo "  run [<flags>]      run program"
echo "  debug [<flags>]    debug program"
libexec/has-routine copy && \
echo "  copy               copy program"
libexec/has-routine paste && \
echo "  paste              paste program"
echo "  save <name>        save program"
echo "  list               list saved programs"
echo "  open <name>        open saved program"
echo "  remove <name>      remove saved program"
echo "  --help             print usage information"
echo "  --version          print version"
echo ""
echo "For full documentation, see: https://github.com/guidanoli/cptk#readme"
