#!/usr/bin/env bash
#
# Summary: prints usage information
#
# Usage: libexec/base/--help

echo "Usage: $programname <command> [<args>]"
echo ""
echo "Some useful commands are:"
echo "  init <language>    set current language"
echo "  path               print program path"
hascommand editcommand && \
echo "  edit               edit program"
echo "  run [<flags>]      run program"
echo "  debug [<flags>]    debug program"
hascommand copycommand && \
echo "  copy               copy program"
hascommand pastecommand && \
echo "  paste              paste program"
echo "  delete             delete program"
echo "  --help             print usage information"
echo "  --version          print version"
echo ""
echo "For full documentation, see: https://github.com/guidanoli/cptk#readme"
