#!/usr/bin/env bash
#
# Summary: prints usage information
#
# Usage: libexec/base/--help

echo "Usage: $programname <command> [<args>]"
echo ""
echo "Commands"
echo "--------"
echo ""
echo "init <language>    set current language"
echo "path               print program path"
command -v editcommand > /dev/null && \
echo "edit               edit program"
echo "run [<flags>]      run program"
echo "debug [<flags>]    debug program"
command -v copycommand > /dev/null && \
echo "copy               copy program"
command -v pastecommand > /dev/null && \
echo "paste              paste program"
echo "--help             print usage information"
echo "--version          print version"
echo ""
echo "Environment variables"
echo "---------------------"
echo ""
echo "EDITOR             text editor"
echo "JAVACLASS          java class name"
echo ""
echo "For full documentation, see: https://github.com/guidanoli/cptk#readme"
