#!/usr/bin/env bash
#
# Summary: Get binary file path of the current language

# Make temporary directory
mkdir -p "lib/$lang/temp"

# Make subcall
bin="$(libexec/subcall "$file" "$@")"

# If call subfails,
if [[ $? -ne 0 ]]; then
	# then exit
	ret=$?
	echo "Internal call to bin failed." >&2
	exit $?
else
	echo "lib/$lang/$bin"
fi
