#!/usr/bin/env bash
#
# Summary: Get binary file path of the current language

# Make temporary directory
mkdir -p "lib/$lang/temp"

# Make subcall
bin="$(libexec/subcall "$file" "$@")"

# Print binary file path
echo "lib/$lang/$bin"
