#!/usr/bin/env bash
#
# Summary: Removes temporary files from the current language
#
# Usage: libexec/base/clear

# Exit on error
set -e

# Get language
lang=$(libexec/get-lang)

# Remove temporary folder
rm -rf "lib/$lang/temp"

