#!/usr/bin/env bash
#
# Summary: Copy contents of source code to clipboard
#
# Usage: libexec/base/clip {OPTIONS}
#
# If on WSL, uses clip.
# Else, uses xclip.

# Make call to src
src="$(libexec/call src "$lang" "$@")"

# If source is missing,
if [[ -z "$src" || ! ( -f "$src" ) ]]; then
	# then exit
	source libexec/err/1
else
	# else, if running on WSL,
	if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
		# run clip.exe
		cat "$src" | clip.exe
	else
		# else, run xclip
		xclip -sel c < "$src"
	fi
fi
