#!/usr/bin/env bash
#
# Summary: Copy contents of source code to clipboard
#
# If on WSL, uses clip.
# Else, uses xclip.

# Get program path
path="$(libexec/base/path)"

# If source is missing,
if [[ ! -f "$path" ]]; then

	# Get language
	lang=$(libexec/get-lang)
	
	# then exit
	source libexec/err/1
else
	# else, if running on WSL,
	if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
		# run clip.exe
		clip.exe < "$path"
	else
		# else, run xclip
		xclip -sel c < "$path"
	fi
fi
