#!/usr/bin/env bash
#
# Summary: Copy contents of source code to clipboard
#
# Usage: libexec/base/clip {OPTIONS}
#
# If on WSL, uses clip.
# Else, uses xclip.

# Make call to path
path="$(libexec/call path "$lang" "$@")"

# If source is missing,
if [[ -z "$path" || ! ( -f "$path" ) ]]; then
	# then exit
	source libexec/err/1
else
	# else, if running on WSL,
	if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
		# run clip.exe
		cat "$path" | clip.exe
	else
		# else, run xclip
		xclip -sel c < "$path"
	fi
fi
