#!/usr/bin/env bash
#
# Summary: Copy contents of source code to clipboard

# Exit on error
set -e

# Get program path
path=$(libexec/base/path)

# If program exists,
if [[ -f "$path" ]]; then

	# if running on WSL,
	if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
		# run clip.exe
		cat "$path" | clip.exe
	else
		# else, run xclip
		cat "$path" | xclip -selection clipboard
	fi
else
	# else, exit
	lang=$(libexec/get-lang)
	source libexec/err/no-program
fi
