#!/usr/bin/env bash
#
# Summary: Copy contents of program

# Exit on error
set -e

# Get program path
path=$(libexec/base/path)

# If program exists
if [[ -f $path ]]
then
	# If copy command is supported
	if hascommand copycommand
	then
		# then copy it
		copycommand "$path"
	else
		# else, exit
		source libexec/err/no-command-support
	fi
else
	# Get language
	lang=$(libexec/get-lang)

	# else, exit
	source libexec/err/no-program
fi
