#!/usr/bin/env bash
#
# Summary: Edits source code of the current language
#
# Usage: libexec/base/edit {OPTIONS}
#
# Opens source code in text editor.

# Make call to path 
path="$(libexec/call path "$lang" "$@")"

# Edit source code
vi "$path"
