#!/usr/bin/env bash
#
# Summary: Edit program

# Exit on error
set -e

# Get program path
path=$(libexec/base/path)

# If edit command is supported
if hascommand editcommand ; then
	# then, edit program
	editcommand "$path"
else
	# else, exit
	source libexec/err/no-command-support
fi
