#!/usr/bin/env bash
#
# Summary: Displays all commands

echo "Competitive Programming Language-Agnostic Toolkit"
echo "These are all the available commands"
echo "bin - get binary file path"
echo "cat - write stdin to source file"
echo "clear - clear temporary folder"
echo "clip - copy source file content to clipboard"
echo "edit - edit source file in vi"
echo "load - load project"
echo "prjlist - list all projects"
echo "run - run program"
echo "rund - run program in debug mode"
echo "save - save project"
echo "src - get source file path"
