#!/usr/bin/env bash
#
# Summary: Creates the .cptk directory and sets a language
#
# Usage: libexec/base/init <language>

# Exit on error
set -e

# If <language> is present
if [[ $# -gt 0 ]]
then
	# Make .cptk directory
	mkdir -p "$userdir"

	# Set language
	libexec/set-lang "$1"
else
	# exit
	argname='<language>'
	source libexec/err/missing-argument
fi
