#!/usr/bin/env bash
#
# Summary: List all saved projects

# Exit on error
set -e

# Get language
lang=$(libexec/get-lang)

# Get language project folder
langprjfolder=etc/projects/$lang

# If folder exists, list all subdirectories
if [[ -d "$langprjfolder" ]]; then
    ls -1 "$langprjfolder"
fi
