#!/usr/bin/env bash
#
# Summary: Load project folder into temp folder
#
# Usage: libexec/base/load <project>

if [[ $# -gt 0 ]]; then

	# Get project name
	project=$1
	shift

	# Get language
	lang=$(libexec/get-lang)

	# Get project folder path
	projectfolder=etc/projects/$lang/$project

	# Check if project folder exists
	if ! [[ -d "$projectfolder" ]]; then
	    # If not, exit
	    source libexec/err/5
	fi

	# Temporary folder
	tempfolder=lib/$lang/temp

	# Copy the project folder contents to the temp folder
	cp -a "$projectfolder/." "$tempfolder"

else

	# else, exit
	argname='<project>'
	source libexec/err/7

fi
