#!/usr/bin/env bash
#
# Summary: Load project folder into temp folder

# Get project name
prj=$1
shift

# Get project folder path
prjfolder="etc/projects/$lang/$prj"

# Check if project folder exists
if ! [[ -d "$prjfolder" ]]; then
    # If not, exit
    source libexec/err/5
fi

# Temporary folder
tempfolder="lib/$lang/temp"

# Copy the project folder contents to the temp folder
cp -a "$prjfolder/." "$tempfolder"
