#!/usr/bin/env bash
#
# Summary: Load project folder into temp folder
#
# Usage: libexec/base/open <project>

# Exit on error
set -e

if [[ $# -gt 0 ]]
then
	# Get project name
	project=$1
	shift

	# Get language
	lang=$(libexec/get-lang)

	# Get projects folder path
	projectsfolder=$userdir/user/$lang

	# If project is not in the projects folder
	if ! libexec/is-child "$projectsfolder" "$project" -type f
	then
		# then, exit
		source libexec/err/unknown-project
	fi

	# Get main program path
	path=$(libexec/base/path)

	# Make sure main program can be written
	mkdir -p "$(dirname "$path")"

	# Make project file be the main program
	cp "$projectsfolder/$project" "$path"

elif [[ $# -eq 0 ]]
then
	# Exit
	argname='<project>'
	source libexec/err/missing-argument
fi
