#!/usr/bin/env bash
#
# Summary: Load project folder into temp folder
#
# Usage: libexec/base/open <project>

# Exit on error
set -e

if [[ $# -eq 1 ]]; then

	# Get project name
	project=$1
	shift

	# Get language
	lang=$(libexec/get-lang)

	# Get project folder path
	projectfolder=etc/projects/$lang/$project

	# Check if project folder exists
	if [[ ! -d "$projectfolder" ]]; then
	    # If not, exit
	    source libexec/err/unknown-project
	fi

	# Copy project files to temporary directory
	cp -a "$projectfolder/." "lib/$lang/temp"

elif [[ $# -eq 0 ]]; then

	# Exit
	argname='<project>'
	source libexec/err/missing-argument

else

	# Unknown argument
	source libexec/err/unknown-arguments

fi
