#!/usr/bin/env bash
#
# Summary: Paste contents of clipboard to program

# Exit on error
set -e

# Get program path
path=$(libexec/base/path)

# Make sure program can be written
mkdir -p "$(dirname "$path")"

# If paste command is supported
if hascommand pastecommand
then
	# then, paste to program
	pastecommand "$path"
else
	# else, exit
	source libexec/err/no-command-support
fi
