#!/usr/bin/env bash
#
# Summary: Pase clipboard to source code

# Exit on error
set -e

# Get program path
path=$(libexec/base/path)

# If running on WSL,
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
	# run paste.exe
	paste.exe > "$path"
else
	# else, run xclip
	xclip -sel c -o > "$path"
fi
