#!/usr/bin/env bash
#
# Summary: Paste contents of clipboard to program

# Exit on error
set -e

# Get program path
path=$(libexec/base/path)

# Make sure program can be written
mkdir -p "$(dirname "$path")"

# Paste to program
libexec/call-routine paste "$path"
