#!/usr/bin/env bash
#
# Summary: Get source code file path of the current language

# Make temporary directory
mkdir -p "lib/$lang/temp"

# Make subcall
path="$(libexec/subcall "$file" "$@")"

# Print source code file path
echo "$PWD/lib/$lang/$path"
