#!/usr/bin/env bash
#
# Summary: Get source code file path of the current language

# Get language
lang=$(libexec/get-lang)

temporaryfolder=lib/$lang/temp

# Make temporary directory
mkdir -p "$temporaryfolder"

# Make subcall
path=$(libexec/subcall path "$@")

# Print source code file path
echo "$PWD/$temporaryfolder/$path"
