#!/usr/bin/env bash
#
# Summary: Get source code file path of the current language

# Exit on error
set -e

# Get language
lang=$(libexec/get-lang)

# Make subcall
path=$(libexec/subcall path)

# Print source code file path
echo "$userdir/main/$lang/$path"
