#!/usr/bin/env bash
#
# Summary: Remove project folder
#
# Usage: libexec/base/remove <project>

# Exit on error
set -e

if [[ $# -gt 0 ]]
then
	# Get project name
	project=$1
	shift

	# Get language
	lang=$(libexec/get-lang)

	# Get projects folder path
	projectsfolder=etc/projects/$lang

	# If project is not in the projects folder
	if ! libexec/is-child "$projectsfolder" "$project" -type d
	then
		# then, exit
		source libexec/err/unknown-project
	fi

	# Remove folder recursively
	rm -rf "$projectsfolder/$project"

elif [[ $# -eq 0 ]]
then
	# Exit
	argname='<project>'
	source libexec/err/missing-argument
fi
