#!/usr/bin/env bash
#
# Summary: Run source code

# Exit on error
set -e

# Make call to path
path=$(libexec/base/path)

# If program exists,
if [[ -f "$path" ]] ; then
	# then make subcall
	libexec/subcall run
else
	# Get language
	lang=$(libexec/get-lang)

	# else exit
	source libexec/err/no-program
fi
