#!/usr/bin/env bash
#
# Summary: Run source code

# Make call to path
path=$(libexec/base/path)

# If source code exists,
if [[ -f "$path" ]] ; then
	# then make subcall
	libexec/subcall run "$@"
else
	# else exit
	source libexec/err/1
fi
