#!/usr/bin/env bash
#
# Summary: Save temp folder to project folder
#
# Usage: libexec/base/save <project>

# Check if <project> is present
if [[ $# -gt 0 ]]; then

	# Get language
	lang=$(libexec/get-lang)

	# Get project folder path
	prjfolder=etc/projects/$lang/$1
	shift

	# Make project folder
	mkdir -p "$prjfolder"

	# Temporary folder
	tempfolder=lib/$lang/temp

	# If temporary folder exists,
	# copy its contents to the project folder
	if [[ -d $tempfolder ]]; then
	    cp -a "$tempfolder/." "$prjfolder"
	fi

else

	# else, exit
	argname='<project>'
	source libexec/err/7

fi
