#!/usr/bin/env bash
#
# Summary: Save temp folder to project folder
#
# Usage: libexec/base/save <project>

# Exit on error
set -e

# Check if <project> is present
if [[ $# -eq 1 ]]; then

	# Get language
	lang=$(libexec/get-lang)

	# Get project folder path
	projectfolder=etc/projects/$lang/$1
	shift

	# Get program path
	path=$(libexec/base/path)

	# Make project directory
	mkdir -p "$projectfolder"

	# Copy program to project directory
	cp -a "$path" "$projectfolder"

elif [[ $# -eq 0 ]]; then

	# else, exit
	argname='<project>'
	source libexec/err/missing-argument

else

	# Unknown argument
	source libexec/err/unknown-arguments

fi
