#!/usr/bin/env bash
#
# Summary: Save temp folder to project folder
#
# Usage: libexec/base/save <project>

# Exit on error
set -e

# Check if <project> is present
if [[ $# -eq 1 ]]; then

	# Get project name
	project=$1
	shift

	# Get language
	lang=$(libexec/get-lang)

	# Get projects folder path
	projectsfolder=etc/projects/$lang

	# Make project directory
	mkdir -p "$projectsfolder/$project"

	# If project is not in the projects folder
	if ! libexec/is-child "$projectsfolder" "$project" -type d ; then
		# then, exit
		source libexec/err/unknown-project
	fi

	# Get program path
	path=$(libexec/base/path)

	# Copy program to project directory
	cp -a "$path" "$projectsfolder/$project"

elif [[ $# -eq 0 ]]; then

	# else, exit
	argname='<project>'
	source libexec/err/missing-argument

else

	# Shift <project>
	shift

	# Unknown argument
	source libexec/err/unknown-arguments

fi
