#!/usr/bin/env bash
#
# Summary: Get source code file path

# Make temporary directory
mkdir -p "lib/$lang/temp"

# Add prefix to path
printf "lib/$lang/"

# Make subcall
libexec/subcall "$file" "$@"
