#!/usr/bin/env bash
#
# Summary: Get compiler program of the current language

# Make temporary directory
mkdir -p "lib/$lang/temp"

# Make subcall
xpath="$(libexec/subcall "$file" "$@")"

# Print compiler program path
echo "$programroot/lib/$lang/$xpath"
