#!/usr/bin/env bash
#
# Summary: Calls base file 
#
# Usage: libexec/call FILE [LANG {OPTIONS}]
#
# If LANG is present, sets it as the current one
# FILE must be a valid base file

# Exit on failure
set -e

# Save file name
file="$1"
shift

# If the language is specified,
# set it as the current one
if [[ $# -gt 0 ]]; then
	libexec/set-lang "$1"
	shift
fi

# Get current language
lang=$(libexec/get-lang)

# Source base file
source "libexec/base/$file"
