#!/usr/bin/env bash
#
# Summary: Get current language
#
# Usage: libexec/get-lang
#
# Obtains current language, if set

# Save language file location
langfile="etc/lang.dat"

# If the language file exists,
if [[ -f "$langfile" ]]; then
	# Get its content and save it
	lang=$(cat "$langfile")
else
	lang=""
fi

# If language is not set,
if [[ -z "$lang" ]]; then
	# then exit
	source libexec/err/2
fi

echo "$lang"
