#!/usr/bin/env bash
#
# Summary: Get current language
#
# Usage: libexec/get-lang
#
# Obtains current language, if set

# If the language file exists,
if [[ -f $userdir/etc/lang ]]
then
	# Get its content and save it
	lang=$(cat "$userdir/etc/lang")
else
	lang=""
fi

# If language is not set,
if [[ -z $lang ]]
then
	# then exit
	source libexec/err/no-language
fi

# If language is invalid,
if ! libexec/is-child lib "$lang" -type d
then
	# then exit
	source libexec/err/unknown-language
fi

echo "$lang"
