#!/usr/bin/env bash
#
# Summary: Sets current language
#
# Usage: libexec/set-lang <language>
#
# <language> is case-insensitive

# Check if <language> is present
if [[ $# -gt 0 ]]; then

	# Save language in lower case
	lang=${1,,}
	shift

	# If there is a folder with this name in 'lib'
	if libexec/is-child lib "$lang" -type d ; then

		# then set it as the current language
		mkdir -p etc
		echo "$lang" > etc/lang
	else
		# else, exit
		source libexec/err/unknown-language
	fi

else

	# else, exit
	argname='<language>'
	source libexec/err/missing-argument

fi
