#!/usr/bin/env bash
#
# Summary: Make a subcall to a language command
#
# Usage: libexec/subcall <command> [<options>]
#
# Garantees to create temporary folder before subcall.

# Exit on failure
set -e

# If <command> is present
if [[ $# -gt 0 ]]; then
	
	# Save command
	command=$1
	shift

	# Get current language
	lang=$(libexec/get-lang)

	# Save the language directory
	# (where all the scripts are)
	langdir=lib/$lang

	# Make temporary directory
	mkdir -p "$langdir/temp"

	# If command is a file in the language directory
	if libexec/is-child "$langdir" "$command" -type f ; then

		# then, push current language directory
		pushd "$langdir" > /dev/null

		# run it and pass any additional options
		"./$command" "$@"

		# and pop directory
		popd > /dev/null
	else
		# else, exit
		source libexec/err/no-language-support
	fi


else

	# else, exit
	argname='<command>'
	source libexec/err/missing-argument

fi