#!/usr/bin/env bash
#
# Summary: Make a subcall to a language command
#
# Usage: libexec/subcall <command> [<options>]

# Exit on failure
set -e

# Save command
command=$1
shift

# Get current language
lang=$(libexec/get-lang)

# Save the language directory
# (where all the scripts are)
langdir=lib/$lang

# Export temporary directory,
# relative to the language directory
# (where all the temp files are)
export tempdir=temp

# Make temporary directory
mkdir -p "$langdir/$tempdir"

# If subfile exists
if [[ -f "$langdir/$command" ]]; then

	# then, push current language directory
	pushd "$langdir" > /dev/null

	# run it and pass any additional options
	"./$command" "$@"

	# and pop directory
	popd > /dev/null
else
	# else, exit
	source libexec/err/3
fi
